# LLM-Powered AI Trading System Configuration

# Data configuration
data:
  symbols: ["AAPL", "MSFT", "GOOGL", "TSLA", "NVDA"]
  start_date: "2023-01-01"
  end_date: "2024-01-31"
  interval: "1d"
  cache_data: true

# LLM model configuration
model:
  default_model: "deepseek/deepseek-chat-v3-0324"  # 默认模型
  fallback_model: "openai/gpt-4o-mini"            # 备用模型
  min_confidence: 0.6
  max_tokens: 500
  temperature: 0.3
  timeout: 30
  max_retries: 3

# Strategy configuration
strategy:
  initial_capital: 100000
  position_size: 0.1
  stop_loss: 0.05
  take_profit: 0.15
  min_confidence: 0.6

# Risk management
risk:
  max_drawdown: 0.15
  max_position_size: 0.2
  correlation_limit: 0.7

# Analysis settings
analysis:
  lookback_days: 30
  include_market_context: true

# Logging
logging:
  level: "ERROR"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"